[package]
name = "fe-uitest"
version = "0.26.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
publish = false

[dependencies]
driver = { path = "../driver", package = "fe-driver" }
hir = { path = "../hir", package = "fe-hir" }
fe-compiler-test-utils = { path = "../test-utils" }
dir-test = "0.3"
wasm-bindgen-test = "0.3"
